#cloud-config
password: ${vm_pass}
chpasswd: { expire: False }
ssh_pwauth: True
hostname: ${vm_uname}
manage_etc_hosts: true

write_files:
  - path: /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
    permissions: '0644'
    content: |
      network: {config: disabled}

  - path: /etc/update-motd.d/99-ulak-message
    permissions: '0755'
    content: |
      #!/bin/bash
      echo ""
      echo "░█░█░█░░░█▀█░█░█░░░█░█░█▀█░█▀▄░█▀▀░█▀▄░█░░░█▀▀░█▀▀░█▄█░█▀▀"
      echo "░█░█░█░░░█▀█░█▀▄░░░█▀█░█▀█░█▀▄░█▀▀░█▀▄░█░░░█▀▀░▀▀█░█░█░█▀▀"
      echo "░▀▀▀░▀▀▀░▀░▀░▀░▀░░░▀░▀░▀░▀░▀▀░░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀"
      echo ""
      echo "############################################ GELISTIRICIYE NOT #####################################################"
      echo ""
      echo "* Eğer makineyi yeni oluşturduysanız, programların tam olarak kurulabilmesi için yaklaşık 10 dakika bekleyin!"
      echo "* Arka planda programların kurulumunu izlemek için /var/log/cloud-init-output.log dosyasına bakabilirsiniz."
      echo "* Programlar kurulduktan sonra makineyi kullanmaya başlayabilirsiniz."
      echo ""
      echo "####################################################################################################################"

  - path: /etc/netplan/new-config.yaml
    permissions: '0644'
    content: |
      network:
          version: 2
          ethernets:
            ens3:
              routes:
                - to: default
                  via: ${fipp}
              dhcp4: true
              nameservers:
                  addresses:
                  - 8.8.8.8

  - path: /var/cache/installation_test.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "############################################ INSTALLATION START ####################################################"

      # disable daemon notification
      sed -i 's/#$nrconf{restart} = '\''i'\'';/$nrconf{restart} = '\''a'\'';/g' /etc/needrestart/needrestart.conf

      # added ulak nameserver
      sudo sed -i 's/^nameserver .*/nameserver 192.168.10.12/' /etc/resolv.conf

      # Zaman dilimi ayarlanıyor
      echo "############################################ SETTING DATE/TIME #####################################################"
      sudo timedatectl set-ntp yes
      sudo timedatectl set-timezone "Asia/Istanbul"

      # added new user
      echo "############################################ USER CONFIG START #####################################################"

      useradd -m -s /usr/bin/bash ${vm_uname}
      echo ${vm_uname}:${vm_pass} | sudo chpasswd
      # /etc/sudoers.d/${vm_uname} Dosyasını yaratarak sudoers dosyasında yapılacak bir hatanın önüne geçiyoruz
      # echo "${vm_uname}  ALL=(ALL) NOPASSWD:ALL" | sudo tee --append /etc/sudoers.d/kullanici
      echo "${vm_uname}  ALL=(ALL:ALL) ALL" | sudo tee --append /etc/sudoers
      echo ${fipp}
      echo ${nfs_ip}
      echo "############################################ USER CONFIG END #######################################################"

      echo "############################################ COMMON SOFTWARE INSTALLATION START ####################################"

      apt-get update -y
      apt-get upgrade -y
      apt-get install -y apt-transport-https curl wget ca-certificates software-properties-common net-tools vim git build-essential sshpass nfs-common

      echo "############################################ COMMON SOFTWARE INSTALLATION END ######################################"

      # docker installation 
      echo "-------------------------------------------- DOCKER INSTALLATION START ---------------------------------------------"

      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      apt-get update

      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      cat <<EOF | sudo tee /etc/docker/daemon.json
      {
        "insecure-registries": ["registry.ulakhaberlesme.com.tr"],
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
      EOF
      sudo systemctl enable docker
      sudo systemctl daemon-reload
      sudo systemctl start docker
      sudo systemctl restart docker

      echo "############################################ DOCKER INSTALLATION ENDED #############################################"

      #k8s 

      echo "############################################ K8S INSTALLATION STARTED ##############################################"
      swapoff -a
      sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

      cat <<EOL | sudo tee /etc/modules-load.d/containerd.conf
      overlay
      br_netfilter
      EOL

      modprobe overlay
      modprobe br_netfilter

      cat <<EOL | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOL

      sysctl --system

      mkdir -p /etc/containerd

      containerd config default | sudo tee /etc/containerd/config.toml

      systemctl restart containerd

      mkdir -p /etc/apt/keyrings 

      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

      echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

      apt update

      apt install -y kubelet kubeadm kubectl

      apt-mark hold kubelet kubeadm kubectl

      echo "############################################ KUBEADM INIT START ####################################################"
      containerd config default | sudo tee /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      systemctl restart containerd

      kubeadm init --pod-network-cidr=10.244.0.0/16 --v=5 --ignore-preflight-errors=all
      echo "############################################ KUBEADM INIT END ######################################################"

      echo "############################################ KUBECTL MKDIR START ###################################################"
      sudo mkdir -p /home/${vm_uname}/.kube
      sudo cp -i /etc/kubernetes/admin.conf /home/${vm_uname}/.kube/config
      sudo chown ${vm_uname}:${vm_uname} /home/${vm_uname}/.kube/config
      echo "############################################ KUBECTL MKDIR ENDED ###################################################"

      echo "############################################ KUBECTL ROOT MKDIR START ##############################################"
      sudo mkdir -p /root/.kube
      sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
      sudo chown root:root /root/.kube/config
      echo "############################################ KUBECTL ROOT MKDIR ENDED ##############################################"

      echo "############################################ KUBECTL MKDIR START ###################################################"
      sudo mkdir -p /.kube
      sudo cp -i /etc/kubernetes/admin.conf /.kube/config
      sudo chown ${vm_uname}:${vm_uname} /.kube/config
      echo "############################################ KUBECTL MKDIR ENDED ###################################################"

      echo "######### DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG ##########"
      echo "##### pwd"
      pwd
      echo "##### ls"
      ls
      echo "##### whoami"
      whoami
      echo "##### ls -al"
      ls -al
      echo "##### printnev"
      printenv
      echo "######### DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG DEBUG ##########"

      kubectl --kubeconfig /.kube/config apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      kubectl --kubeconfig /.kube/config taint nodes --all node-role.kubernetes.io/control-plane-

      echo "############################################ HELM INSTALLATION START ###############################################"
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      chmod +x get_helm.sh      
      ./get_helm.sh
      helm repo add chartmuseum http://helmchart.ulakhaberlesme.com.tr
      helm repo update
      echo "############################################ HELM INSTALLATION ENDED ###############################################"

      echo "############################################ K8s INSTALLATION ENDED ################################################"

      echo "############################################ DOCKER GROUP START ####################################################"
      groupadd docker
      sudo chmod 777 /var/run/docker.sock
      sudo usermod -aG docker ${vm_uname}
      echo "############################################ DOCKER GROUP END ######################################################"

      echo "############################################ NFS CONFIGURATION START ###############################################"
      # Configure NFS to allow data storage from new VM
      sshpass -p ${nfs_password} ssh -o StrictHostKeyChecking=no ${nfs_username}@${nfs_ip} 'echo "/mnt/nfs ${fipp}(rw,sync,no_root_squash,no_subtree_check)" >> /etc/exports'
      sshpass -p ${nfs_password} ssh -o StrictHostKeyChecking=no ${nfs_username}@${nfs_ip} 'sudo exportfs -a'
      echo "############################################ NFS CONFIGURATION END #################################################"

      echo "############################################ CLONE HELMCHART REPO START ############################################"
      # Clone HelmChart Repository
      git clone http://${gitlab_token_name}:${gitlab_token}@gitlab.ulakhaberlesme.com.tr/DevOps/5gcn-helmchart.git 5gcn_helmchart

      # Apply NFS Provisioner Pod
      cd /5gcn_helmchart/nfs-provisioner && kubectl --kubeconfig /.kube/config apply -k .
      echo "############################################ CLONE HELMCHART REPO END ##############################################"

      echo "############################################ DOCKER REGISTRY ADD START #############################################"
      perl -i -p0e 's/      \[plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors\]/      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]\n        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.ulakhaberlesme.com.tr"]\n          endpoint = ["http:\/\/registry.ulakhaberlesme.com.tr"]/igs' /etc/containerd/config.toml
      perl -i -p0e 's/      \[plugins.\"io.containerd.grpc.v1.cri\".registry.configs\]/      [plugins."io.containerd.grpc.v1.cri".registry.configs]\n        [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.ulakhaberlesme.com.tr".tls]\n          insecure_skip_verify = true/igs' /etc/containerd/config.toml
      systemctl restart containerd
      echo "############################################ DOCKER REGISTRY ADD END ###############################################"

      echo "############################################ UPDATE BASHRC START ###################################################"

      find /home -type f -name ".bashrc" | while read -r file; do
        echo 'alias k="kubectl"' >> $file
        echo 'alias kp="kubectl get pods"' >> $file
        echo 'alias kd="kubectl describe"' >> $file
        echo 'alias kl="kubectl logs"' >> $file
        echo 'alias kg="kubectl get"' >> $file
        echo 'alias keit="kubectl exec -it"' >> $file

        echo 'alias k5="kubectl -n $(namespaces=$(kubectl get namespaces -o jsonpath='"'"'{.items[*].metadata.name}'"'"'); for namespace in $namespaces; do if [[ $namespace == *5gcn-deployment* ]]; then echo $namespace; fi; done)"' >> $file
        echo 'alias k5p="k5 get pods"' >> $file
        echo 'alias k5d="k5 describe"' >> $file
        echo 'alias k5l="k5 logs"' >> $file

        echo 'alias km="kubectl -n monitoring"' >> $file
        echo 'alias kmp="km get pods"' >> $file
        echo 'alias kmd="km describe"' >> $file
        echo 'alias kml="km logs"' >> $file

        echo 'alias hi="helm install"' >> $file
        echo 'alias hu="helm uninstall"' >> $file

        echo 'alias hm="helm -n monitoring"' >> $file
        echo 'alias hmi="hm install"' >> $file
        echo 'alias hmu="hm uninstall"' >> $file

        echo 'alias h5="helm -n $(namespaces=$(kubectl get namespaces -o jsonpath='"'"'{.items[*].metadata.name}'"'"'); for namespace in $namespaces; do if [[ $namespace == *5gcn-deployment* ]]; then echo $namespace; fi; done)"' >> $file
        echo 'alias h5i="h5 install"' >> $file
        echo 'alias h5u="h5 uninstall"' >> $file
      done

      find /root -type f -name ".bashrc" | while read -r file; do
        echo 'alias k="kubectl"' >> $file
        echo 'alias kp="kubectl get pods"' >> $file
        echo 'alias kd="kubectl describe"' >> $file
        echo 'alias kl="kubectl logs"' >> $file
        echo 'alias kg="kubectl get"' >> $file
        echo 'alias keit="kubectl exec -it"' >> $file

        echo 'alias k5="kubectl -n $(namespaces=$(kubectl get namespaces -o jsonpath='"'"'{.items[*].metadata.name}'"'"'); for namespace in $namespaces; do if [[ $namespace == *5gcn-deployment* ]]; then echo $namespace; fi; done)"' >> $file
        echo 'alias k5p="k5 get pods"' >> $file
        echo 'alias k5d="k5 describe"' >> $file
        echo 'alias k5l="k5 logs"' >> $file

        echo 'alias km="kubectl -n monitoring"' >> $file
        echo 'alias kmp="km get pods"' >> $file
        echo 'alias kmd="km describe"' >> $file
        echo 'alias kml="km logs"' >> $file

        echo 'alias hi="helm install"' >> $file
        echo 'alias hu="helm uninstall"' >> $file

        echo 'alias hm="helm -n monitoring"' >> $file
        echo 'alias hmi="hm install"' >> $file
        echo 'alias hmu="hm uninstall"' >> $file

        echo 'alias h5="helm -n $(namespaces=$(kubectl get namespaces -o jsonpath='"'"'{.items[*].metadata.name}'"'"'); for namespace in $namespaces; do if [[ $namespace == *5gcn-deployment* ]]; then echo $namespace; fi; done)"' >> $file
        echo 'alias h5i="h5 install"' >> $file
        echo 'alias h5u="h5 uninstall"' >> $file
      done
      echo "############################################ UPDATE BASHRC END #####################################################"

      echo "############################################ UPDATE KUBELET CONFIG START ###########################################"
      wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod +x /usr/local/bin/yq
      yq eval -i '.spec.containers[0].command += "--service-node-port-range=30000-39000"' /etc/kubernetes/manifests/kube-apiserver.yaml
      systemctl restart kubelet
      echo "############################################ UPDATE KUBELET CONFIG END #############################################"

      echo "############################################ HELM REPO CONFIG START ################################################"
      mkdir -p /root/.config/helm
      mkdir -p /root/.cache/helm
      sudo cp -R /.config/helm/* /root/.config/helm
      sudo cp -R /.cache/helm/* /root/.cache/helm
      sudo chmod 777 /root/.config/helm/*
      sudo chmod 777 /root/.cache/helm/*

      mkdir -p /home/${vm_uname}/.config/helm
      mkdir -p /home/${vm_uname}/.cache/helm
      sudo cp -R /.config/helm/* /home/${vm_uname}/.config/helm
      sudo cp -R /.cache/helm/* /home/${vm_uname}/.cache/helm
      sudo chmod 777 /home/${vm_uname}/.config/helm/*
      sudo chmod 777 /home/${vm_uname}/.cache/helm/*
      echo "############################################ HELM REPO CONFIG END ##################################################"

      
      echo "############################################ INSTALLATION ENDED ####################################################"

runcmd:
  - rm /etc/netplan/50-cloud-init.yaml
  - netplan generate
  - netplan apply
  - [sh, '/var/cache/installation_test.sh']
